const programs = [
  {
    id: 1,
    coverImg: "c1",
    name: "Name of Program1",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2024-12-01",
    category: "IT & AI",
  },
  {
    id: 2,
    coverImg: "c2",
    name: "Name of Program2",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2024-12-05",
    category: "Branding",
  },
  {
    id: 3,
    coverImg: "c3",
    name: "Name of Program3",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2024-12-10",
    category: "Business",
  },
  {
    id: 4,
    coverImg: "c4",
    name: "Name of Program4",
    level: "Beginner",
    type: "Online",
    duration: 19,
    price: 850,
    status: "Available",
    publishDate: "2024-12-15",
    category: "Management & Leadership",
  },
  {
    id: 5,
    coverImg: "c1",
    name: "Name of Program5",
    level: "Beginner",
    type: "Webinar",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2024-12-20",
    category: "Marketing & Sales",
  },
  {
    id: 6,
    coverImg: "c2",
    name: "Name of Program6",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2024-12-25",
    category: "Other",
  },
  {
    id: 7,
    coverImg: "c4",
    name: "Name of Program7",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-01-01",
    category: "IT & AI",
  },
  {
    id: 8,
    coverImg: "c1",
    name: "Name of Program8",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Sold Out",
    publishDate: "2025-01-05",
    category: "Branding",
  },
  {
    id: 9,
    coverImg: "c2",
    name: "Name of Program9",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-01-10",
    category: "Business",
  },
  {
    id: 10,
    coverImg: "c3",
    name: "Name of Program10",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-01-15",
    category: "Management & Leadership",
  },
  {
    id: 11,
    coverImg: "c4",
    name: "Name of Program11",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-01-20",
    category: "Marketing & Sales",
  },
  {
    id: 12,
    coverImg: "c1",
    name: "Name of Program12",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-01-25",
    category: "Other",
  },
  {
    id: 13,
    coverImg: "c2",
    name: "Name of Program13",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-02-01",
    category: "IT & AI",
  },
  {
    id: 14,
    coverImg: "c3",
    name: "Name of Program14",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-02-05",
    category: "Branding",
  },
  {
    id: 15,
    coverImg: "c4",
    name: "Name of Program15",
    level: "Beginner",
    type: "Online",
    duration: 19,
    price: 850,
    status: "Available",
    publishDate: "2025-02-10",
    category: "Business",
  },
  {
    id: 16,
    coverImg: "c1",
    name: "Name of Program16",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-02-15",
    category: "Management & Leadership",
  },
  {
    id: 17,
    coverImg: "c2",
    name: "Name of Program17",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-02-20",
    category: "Marketing & Sales",
  },
  {
    id: 18,
    coverImg: "c4",
    name: "Name of Program18",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-02-25",
    category: "Other",
  },
  {
    id: 19,
    coverImg: "c1",
    name: "Name of Program19",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Sold Out",
    publishDate: "2025-03-01",
    category: "IT & AI",
  },
  {
    id: 20,
    coverImg: "c2",
    name: "Name of Program20",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-03-05",
    category: "Branding",
  },
  {
    id: 21,
    coverImg: "c3",
    name: "Name of Program21",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-03-10",
    category: "Business",
  },
  {
    id: 22,
    coverImg: "c4",
    name: "Name of Program22",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-03-15",
    category: "Management & Leadership",
  },
  {
    id: 23,
    coverImg: "c1",
    name: "Name of Program23",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-03-20",
    category: "Marketing & Sales",
  },
  {
    id: 24,
    coverImg: "c2",
    name: "Name of Program24",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-03-25",
    category: "Other",
  },
  {
    id: 25,
    coverImg: "c3",
    name: "Name of Program25",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-04-01",
    category: "IT & AI",
  },
  {
    id: 26,
    coverImg: "c4",
    name: "Name of Program26",
    level: "Beginner",
    type: "Online",
    duration: 19,
    price: 850,
    status: "Available",
    publishDate: "2025-04-05",
    category: "Branding",
  },
  {
    id: 27,
    coverImg: "c1",
    name: "Name of Program27",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-04-10",
    category: "Business",
  },
  {
    id: 28,
    coverImg: "c2",
    name: "Name of Program28",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-04-15",
    category: "Management & Leadership",
  },
  {
    id: 29,
    coverImg: "c4",
    name: "Name of Program29",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-04-20",
    category: "Marketing & Sales",
  },
  {
    id: 30,
    coverImg: "c1",
    name: "Name of Program30",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Sold Out",
    publishDate: "2025-04-25",
    category: "Other",
  },
  {
    id: 31,
    coverImg: "c2",
    name: "Name of Program31",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-04-27",
    category: "IT & AI",
  },
  {
    id: 32,
    coverImg: "c3",
    name: "Name of Program32",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-04-29",
    category: "Branding",
  },
  {
    id: 33,
    coverImg: "c1",
    name: "Introduction to crypto currencies",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-05-01",
    category: "Business",
  },
];

const events = [
  {
    id: 1,
    coverImg: "e1",
    name: "Name of Event1",
    level: "Beginner",
    type: "Event",
    duration: 2, // example: 2 hours
    price: 650, // assuming free
    status: "Scheduled",
    publishDate: "2024-09-17",
    category: "General",
  },
  {
    id: 2,
    coverImg: "e2",
    name: "Name of Event2",
    level: "Beginner",
    type: "Event",
    duration: 2,
    price: 650,
    status: "Scheduled",
    publishDate: "2025-04-25",
    category: "General",
  },
  {
    id: 3,
    coverImg: "e3",
    name: "Name of Event3",
    level: "Beginner",
    type: "Event",
    duration: 2,
    price: 650,
    status: "Scheduled",
    publishDate: "2025-04-20",
    category: "General",
  },
  {
    id: 4,
    coverImg: "e4",
    name: "Web Search",
    level: "Beginner",
    type: "Event",
    duration: 2,
    price: 650,
    status: "Scheduled",
    publishDate: "2025-05-08",
    category: "General",
  },
];

const posts = [
  {
    id: 1,
    coverImg: "np1",
    name: "Name of News",
    level: "N/A",
    type: "NEWS",
    duration: 0,
    price: 0,
    status: "Published",
    publishDate: "2024-08-06",
    category: "Announcements",
  },
  {
    id: 2,
    coverImg: "np2",
    name: "Name of Post",
    level: "N/A",
    type: "POST",
    duration: 0,
    price: 0,
    status: "Published",
    publishDate: "2024-08-06",
    category: "Blog",
  },
  {
    id: 3,
    coverImg: "np3",
    name: "Name of News",
    level: "N/A",
    type: "NEWS",
    duration: 0,
    price: 0,
    status: "Published",
    publishDate: "2024-08-06",
    category: "Announcements",
  },
  {
    id: 4,
    coverImg: "np4",
    name: "Name of Post",
    level: "N/A",
    type: "POST",
    duration: 0,
    price: 0,
    status: "Published",
    publishDate: "2024-08-06",
    category: "Blog",
  },
];

const categories = [
  { id: 1, label: "IT & AI" },
  { id: 2, label: "Branding" },
  { id: 3, label: "Business" },
  { id: 4, label: "Management & Leadership" },
  { id: 5, label: "Marketing & Sales" },
  { id: 6, label: "Other" },
];

export { programs, events, posts, categories };
