const programs = [
  {
    id: 1,
    coverImg: "c1",
    name: "Name of Program1",
    level: "Beginner",
    type: "Self Study",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2024-12-01",
    category: "IT & AI",
  },
  {
    id: 2,
    coverImg: "c2",
    name: "Name of Program2",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2024-12-05",
    category: "Branding",
  },
  {
    id: 3,
    coverImg: "c3",
    name: "Name of Program3",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2024-12-10",
    category: "Business",
  },
  {
    id: 4,
    coverImg: "c4",
    name: "Name of Program4",
    level: "Beginner",
    type: "Online",
    duration: 19,
    price: 850,
    status: "Available",
    publishDate: "2024-12-15",
    category: "Management & Leadership",
  },
  {
    id: 5,
    coverImg: "c1",
    name: "Name of Program5",
    level: "Beginner",
    type: "Webinar",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2024-12-20",
    category: "Marketing & Sales",
  },
  {
    id: 6,
    coverImg: "c2",
    name: "Name of Program6",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2024-12-25",
    category: "Other",
  },
  {
    id: 7,
    coverImg: "c4",
    name: "Name of Program7",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-01-01",
    category: "IT & AI",
  },
  {
    id: 8,
    coverImg: "c1",
    name: "Name of Program8",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Sold Out",
    publishDate: "2025-01-05",
    category: "Branding",
  },
  {
    id: 9,
    coverImg: "c2",
    name: "Name of Program9",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-01-10",
    category: "Business",
  },
  {
    id: 10,
    coverImg: "c3",
    name: "Name of Program10",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-01-15",
    category: "Management & Leadership",
  },
  {
    id: 11,
    coverImg: "c4",
    name: "Name of Program11",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-01-20",
    category: "Marketing & Sales",
  },
  {
    id: 12,
    coverImg: "c1",
    name: "Name of Program12",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-01-25",
    category: "Other",
  },
  {
    id: 13,
    coverImg: "c2",
    name: "Name of Program13",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-02-01",
    category: "IT & AI",
  },
  {
    id: 14,
    coverImg: "c3",
    name: "Name of Program14",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-02-05",
    category: "Branding",
  },
  {
    id: 15,
    coverImg: "c4",
    name: "Name of Program15",
    level: "Beginner",
    type: "Online",
    duration: 19,
    price: 850,
    status: "Available",
    publishDate: "2025-02-10",
    category: "Business",
  },
  {
    id: 16,
    coverImg: "c1",
    name: "Name of Program16",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-02-15",
    category: "Management & Leadership",
  },
  {
    id: 17,
    coverImg: "c2",
    name: "Name of Program17",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-02-20",
    category: "Marketing & Sales",
  },
  {
    id: 18,
    coverImg: "c4",
    name: "Name of Program18",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-02-25",
    category: "Other",
  },
  {
    id: 19,
    coverImg: "c1",
    name: "Name of Program19",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Sold Out",
    publishDate: "2025-03-01",
    category: "IT & AI",
  },
  {
    id: 20,
    coverImg: "c2",
    name: "Name of Program20",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-03-05",
    category: "Branding",
  },
  {
    id: 21,
    coverImg: "c3",
    name: "Name of Program21",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-03-10",
    category: "Business",
  },
  {
    id: 22,
    coverImg: "c4",
    name: "Name of Program22",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-03-15",
    category: "Management & Leadership",
  },
  {
    id: 23,
    coverImg: "c1",
    name: "Name of Program23",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-03-20",
    category: "Marketing & Sales",
  },
  {
    id: 24,
    coverImg: "c2",
    name: "Name of Program24",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-03-25",
    category: "Other",
  },
  {
    id: 25,
    coverImg: "c3",
    name: "Name of Program25",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-04-01",
    category: "IT & AI",
  },
  {
    id: 26,
    coverImg: "c4",
    name: "Name of Program26",
    level: "Beginner",
    type: "Online",
    duration: 19,
    price: 850,
    status: "Available",
    publishDate: "2025-04-05",
    category: "Branding",
  },
  {
    id: 27,
    coverImg: "c1",
    name: "Name of Program27",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-04-10",
    category: "Business",
  },
  {
    id: 28,
    coverImg: "c2",
    name: "Name of Program28",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-04-15",
    category: "Management & Leadership",
  },
  {
    id: 29,
    coverImg: "c4",
    name: "Name of Program29",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-04-20",
    category: "Marketing & Sales",
  },
  {
    id: 30,
    coverImg: "c1",
    name: "Name of Program30",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Sold Out",
    publishDate: "2025-04-25",
    category: "Other",
  },
  {
    id: 31,
    coverImg: "c2",
    name: "Name of Program31",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-04-27",
    category: "IT & AI",
  },
  {
    id: 32,
    coverImg: "c3",
    name: "Name of Program32",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-04-29",
    category: "Branding",
  },
  {
    id: 33,
    coverImg: "c1",
    name: "Introduction to crypto currencies",
    level: "Beginner",
    type: "Online",
    duration: 20,
    price: 850,
    status: "Available",
    publishDate: "2025-05-01",
    category: "Business",
  },
];

const events = [
  {
    id: 1,
    coverImg: "e1",
    name: "Name of Event1",
    level: "Beginner",
    type: "Event",
    duration: 2, // example: 2 hours
    price: 650, // assuming free
    status: "Scheduled",
    publishDate: "2024-09-17",
    category: "General",
  },
  {
    id: 2,
    coverImg: "e2",
    name: "Name of Event2",
    level: "Beginner",
    type: "Event",
    duration: 2,
    price: 650,
    status: "Scheduled",
    publishDate: "2025-04-25",
    category: "General",
  },
  {
    id: 3,
    coverImg: "e3",
    name: "Name of Event3",
    level: "Beginner",
    type: "Event",
    duration: 2,
    price: 650,
    status: "Scheduled",
    publishDate: "2025-04-20",
    category: "General",
  },
  {
    id: 4,
    coverImg: "e4",
    name: "Web Search",
    level: "Beginner",
    type: "Event",
    duration: 2,
    price: 650,
    status: "Scheduled",
    publishDate: "2025-05-08",
    category: "General",
  },
  {
    id: 5,
    coverImg: "e4",
    name: "Web Search",
    level: "Beginner",
    type: "Event",
    duration: 2,
    price: 650,
    status: "Scheduled",
    publishDate: "2025-05-08",
    category: "General",
  },
  {
    id: 6,
    coverImg: "e4",
    name: "Web Search",
    level: "Beginner",
    type: "Event",
    duration: 2,
    price: 650,
    status: "Scheduled",
    publishDate: "2025-05-08",
    category: "General",
  },
  {
    id: 7,
    coverImg: "e4",
    name: "Web Search",
    level: "Beginner",
    type: "Event",
    duration: 2,
    price: 650,
    status: "Scheduled",
    publishDate: "2025-05-08",
    category: "General",
  },
  {
    id: 8,
    coverImg: "e4",
    name: "Web Search",
    level: "Beginner",
    type: "Event",
    duration: 2,
    price: 650,
    status: "Scheduled",
    publishDate: "2025-05-08",
    category: "General",
  },
  {
    id: 9,
    coverImg: "e4",
    name: "Web Search",
    level: "Beginner",
    type: "Event",
    duration: 2,
    price: 650,
    status: "Scheduled",
    publishDate: "2025-05-08",
    category: "General",
  },
  {
    id: 10,
    coverImg: "e4",
    name: "Web Search",
    level: "Beginner",
    type: "Event",
    duration: 2,
    price: 650,
    status: "Scheduled",
    publishDate: "2025-05-08",
    category: "General",
  },
  {
    id: 11,
    coverImg: "e4",
    name: "Web Search",
    level: "Beginner",
    type: "Event",
    duration: 2,
    price: 650,
    status: "Scheduled",
    publishDate: "2025-05-08",
    category: "General",
  },
  {
    id: 12,
    coverImg: "e4",
    name: "Web Search",
    level: "Beginner",
    type: "Event",
    duration: 2,
    price: 650,
    status: "Scheduled",
    publishDate: "2025-05-08",
    category: "General",
  },
  {
    id: 13,
    coverImg: "e4",
    name: "Web Search",
    level: "Beginner",
    type: "Event",
    duration: 2,
    price: 650,
    status: "Scheduled",
    publishDate: "2025-05-08",
    category: "General",
  },
  {
    id: 14,
    coverImg: "e4",
    name: "Web Search",
    level: "Beginner",
    type: "Event",
    duration: 2,
    price: 650,
    status: "Scheduled",
    publishDate: "2025-05-08",
    category: "General",
  },
];

const posts = [
  {
    id: 1,
    coverImg: "np1",
    name: "Name of News",
    level: "N/A",
    type: "NEWS",
    duration: 0,
    price: 0,
    status: "Published",
    publishDate: "2024-08-06",
    category: "Announcements",
  },
  {
    id: 2,
    coverImg: "np2",
    name: "Name of Post",
    level: "N/A",
    type: "POST",
    duration: 0,
    price: 0,
    status: "Published",
    publishDate: "2024-08-06",
    category: "Blog",
  },
  {
    id: 3,
    coverImg: "np3",
    name: "Name of News",
    level: "N/A",
    type: "NEWS",
    duration: 0,
    price: 0,
    status: "Published",
    publishDate: "2024-08-06",
    category: "Announcements",
  },
  {
    id: 4,
    coverImg: "np4",
    name: "Name of Post",
    level: "N/A",
    type: "POST",
    duration: 0,
    price: 0,
    status: "Published",
    publishDate: "2024-08-06",
    category: "Blog",
  },
];

const news = [
  {
    id: 0,
    coverImg: "np1",
    title: "This is a title for slider",
    mainDesc:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    category: "NEWS",
    like: 253,
    comments: 26,
    author: "Reza Bidari",
    publishDate: "2024-12-01",
    description1: [
      {
        id: 11,
        title: "Title Of Lesson",
        content:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed ",
        cover: "c1",
      },
      {
        id: 12,
        title: "Title Of Lesson",
        content:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed ",
        cover: "c1",
      },
    ],
  },
  {
    id: 1,
    coverImg: "np1",
    title: "1 Lorem ipsum dolor sit amet, consectetur adipiscing elit ",
    mainDesc:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    category: "NEWS",
    like: 253,
    comments: 26,
    author: "Reza Bidari",
    publishDate: "2024-12-01",
    description1: [
      {
        id: 11,
        title: "Title Of Lesson",
        content:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. @(*Ullamcorper*)@ velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed ",
        cover: "c1",
      },
      {
        id: 12,
        title: "Title Of Lesson",
        content:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed ",
        cover: "c1",
      },
    ],
  },
  {
    id: 2,
    coverImg: "np3",
    title: "2 Lorem ipsum dolor sit amet, consectetur adipiscing elit ",
    mainDesc:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    category: "NEWS",
    like: 253,
    comments: 26,
    author: "Reza Bidari",
    publishDate: "2024-12-01",
    description1: [
      {
        id: 21,
        title: "Title Of Lesson",
        content:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed ",
        cover: "c1",
      },
      {
        id: 22,
        title: "Title Of Lesson",
        content:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed ",
        cover: "c1",
      },
    ],
  },
  {
    id: 3,
    coverImg: "np3",
    title: "3 Lorem ipsum dolor sit amet, consectetur adipiscing elit ",
    mainDesc:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    category: "NEWS",
    like: 253,
    comments: 26,
    author: "Reza Bidari",
    publishDate: "2024-12-01",
    description1: [
      {
        id: 31,
        title: "Title Of Lesson",
        content:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed ",
        cover: "c1",
      },
      {
        id: 32,
        title: "Title Of Lesson",
        content:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed ",
        cover: "c1",
      },
    ],
  },
  {
    id: 4,
    coverImg: "np3",
    title: "4 Lorem ipsum dolor sit amet, consectetur adipiscing elit ",
    mainDesc:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    category: "NEWS",
    like: 253,
    comments: 26,
    author: "Reza Bidari",
    publishDate: "2024-12-01",
    description1: [
      {
        id: 41,
        title: "Title Of Lesson",
        content:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed ",
        cover: "c1",
      },
      {
        id: 42,
        title: "Title Of Lesson",
        content:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed ",
        cover: "c1",
      },
    ],
  },
  {
    id: 5,
    coverImg: "np3",
    title: "5 Lorem ipsum dolor sit amet, consectetur adipiscing elit ",
    mainDesc:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    category: "NEWS",
    like: 253,
    comments: 26,
    author: "Reza Bidari",
    publishDate: "2024-12-01",
    description1: [
      {
        id: 51,
        title: "Title Of Lesson",
        content:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed ",
        cover: "c1",
      },
      {
        id: 52,
        title: "Title Of Lesson",
        content:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed ",
        cover: "c1",
      },
    ],
  },
  {
    id: 6,
    coverImg: "np3",
    title: "6 Lorem ipsum dolor sit amet, consectetur adipiscing elit ",
    mainDesc:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    category: "NEWS",
    like: 253,
    comments: 26,
    author: "Reza Bidari",
    publishDate: "2024-12-01",
    description1: [
      {
        id: 61,
        title: "Title Of Lesson",
        content:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed ",
        cover: "c1",
      },
      {
        id: 62,
        title: "Title Of Lesson",
        content:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et molestie ac feugiat sed ",
        cover: "c1",
      },
    ],
  },
];

const categories = [
  { id: 0, label: "All" },
  { id: 1, label: "IT & AI" },
  { id: 2, label: "Branding" },
  { id: 3, label: "Business" },
  { id: 4, label: "Management & Leadership" },
  { id: 5, label: "Marketing & Sales" },
  { id: 6, label: "Other" },
];

const newsGroups = [
  { id: 0, label: "All" },
  { id: 1, label: "Group1" },
  { id: 2, label: "Group2" },
  { id: 3, label: "Group3" },
  { id: 4, label: "Group4" },
  { id: 5, label: "Group5" },
  { id: 6, label: "Group6" },
  { id: 7, label: "Group7" },
  { id: 8, label: "Group8" },
];

const transactions = [
  {
    program: "Frontend Mastery",
    date: "01/05/2025",
    amount: "$920 (CAD)",
    payType: "PayPal",
    status: "Success",
    transactionId: "tx001a9zbc",
  },
  {
    program: "Backend Bootcamp",
    date: "03/05/2025",
    amount: "$870 (CAD)",
    payType: "PayPal",
    status: "Success",
    transactionId: "tx002bx7dp",
  },
  {
    program: "Fullstack Pro",
    date: "04/05/2025",
    amount: "$960 (CAD)",
    payType: "PayPal",
    status: "Success",
    transactionId: "tx003cr8jf",
  },
  {
    program: "AI Fundamentals",
    date: "06/05/2025",
    amount: "$1050 (CAD)",
    payType: "PayPal",
    status: "Success",
    transactionId: "tx004df2qw",
  },
  {
    program: "UX/UI Essentials",
    date: "02/03/2025",
    amount: "$780 (CAD)",
    payType: "PayPal",
    status: "Success",
    transactionId: "tx005ez3km",
  },
  {
    program: "React Native Lab",
    date: "05/05/2025",
    amount: "$890 (CAD)",
    payType: "PayPal",
    status: "Success",
    transactionId: "tx006fj6bn",
  },
  {
    program: "DevOps Workshop",
    date: "02/04/2025",
    amount: "$830 (CAD)",
    payType: "PayPal",
    status: "Success",
    transactionId: "tx007gs1re",
  },
  {
    program: "Data Science Intro",
    date: "05/05/2021",
    amount: "$950 (CAD)",
    payType: "PayPal",
    status: "Success",
    transactionId: "tx008hr5uy",
  },
  {
    program: "Cybersecurity Basics",
    date: "02/04/2020",
    amount: "$870 (CAD)",
    payType: "PayPal",
    status: "Success",
    transactionId: "tx009id7lt",
  },
  {
    program: "Cybersecurity Basics",
    date: "02/04/2020",
    amount: "$870 (CAD)",
    payType: "PayPal",
    status: "Success",
    transactionId: "tx009id7lt",
  },
  {
    program: "Cybersecurity Basics",
    date: "02/04/2020",
    amount: "$870 (CAD)",
    payType: "PayPal",
    status: "Success",
    transactionId: "tx009id7lt",
  },
  {
    program: "Cybersecurity Basics",
    date: "02/04/2020",
    amount: "$870 (CAD)",
    payType: "PayPal",
    status: "Success",
    transactionId: "tx009id7lt",
  },
  {
    program: "Cybersecurity Basicsssssss",
    date: "02/04/2020",
    amount: "$870 (CAD)",
    payType: "PayPal",
    status: "Success",
    transactionId: "tx009id7lt",
  },
];

const jobOffers = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "PixelWave",
    location: "Toronto, ON",
    isRemote: true,
    isDisabilityFriendly: true,
    postedAt: "2025-05-12T22:00:00",
    ratePerhour: "50 - 75",
    jobGroup: "Remote",
  },
  {
    id: 2,
    title: "Backend Developer",
    company: "CodeCrafters",
    location: "Vancouver, BC",
    isRemote: false,
    isDisabilityFriendly: true,
    postedAt: "2025-04-28T14:30:00",
    ratePerhour: "60 - 80",
    jobGroup: "IT",
  },
  {
    id: 3,
    title: "UI-UX Designer",
    company: "Designify",
    location: "Montreal, QC",
    isRemote: true,
    isDisabilityFriendly: false,
    postedAt: "2025-05-08T09:00:00",
    ratePerhour: "45 - 70",
    jobGroup: "Remote",
  },
  {
    id: 4,
    title: "DevOps Engineer",
    company: "CloudNest",
    location: "Calgary, AB",
    isRemote: false,
    isDisabilityFriendly: true,
    postedAt: "2024-05-05T13:45:00",
    ratePerhour: "55 - 85",
    jobGroup: "IT",
  },
  {
    id: 5,
    title: "Fullstack Engineer",
    company: "StackStudio",
    location: "Ottawa, ON",
    isRemote: true,
    isDisabilityFriendly: true,
    postedAt: "2025-05-09T16:00:00",
    ratePerhour: "65 - 90",
    jobGroup: "Crypto",
  },
  {
    id: 6,
    title: "Mobile App Developer",
    company: "AppForge",
    location: "Halifax, NS",
    isRemote: true,
    isDisabilityFriendly: false,
    postedAt: "2025-05-11T08:30:00",
    ratePerhour: "50 - 78",
    jobGroup: "Remote",
  },
  {
    id: 7,
    title: "QA Analyst",
    company: "Testopia",
    location: "Winnipeg, MB",
    isRemote: false,
    isDisabilityFriendly: true,
    postedAt: "2025-05-07T11:10:00",
    ratePerhour: "40 - 65",
    jobGroup: "IT",
  },
];

const comments = [
  {
    id: 1,
    title: "Title of comment",
    author: "Biran amri",
    date: "2025-05-08",
    text: "Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat duis.",
    rating: 4,
    likes: 12,
    disLike: 2,
  },
  {
    id: 2,
    title: "Title of comment",
    author: "Biran amri",
    date: "2025-05-08",
    text: "Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat duis.",
    rating: 4,
    likes: 12,
    disLike: 2,
  },
  {
    id: 3,
    title: "Title of comment",
    author: "Biran amri",
    date: "2025-05-08",
    text: "Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat duis.",
    rating: 4,
    likes: 12,
    disLike: 2,
  },
  {
    id: 4,
    title: "Title of comment",
    author: "Biran amri",
    date: "2025-05-08",
    text: "Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat duis.",
    rating: 4,
    likes: 12,
    disLike: 2,
  },
  {
    id: 5,
    title: "Title of comment",
    author: "Biran amri",
    date: "2025-05-08",
    text: "Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat duis.",
    rating: 4,
    likes: 12,
    disLike: 2,
  },
];

const headerMenus = [
  {
    id: 1,
    href: "/programs",
    name: "Programs",
    subMenus: [
      {
        id: 11,
        href: "/programs",
        name: "All Courses",
        desc: null,
      },
      {
        id: 12,
        href: `/programs?type=${encodeURIComponent("Attendance")}`,
        name: "Attendance Courses",
        desc: null,
      },
      {
        id: 13,
        href: `/programs?type=${encodeURIComponent("Online")}`,
        name: "Online Courses",
        desc: null,
      },
      {
        id: 14,
        href: `/programs?type=${encodeURIComponent("Self Study")}`,
        name: "Self-Study Courses",
        desc: null,
      },
    ],
  },
  {
    id: 2,
    href: "/apply",
    name: "Apply",
    subMenus: [],
  },
  {
    id: 3,
    href: "/extra-educational",
    name: "Extra Educational",
    subMenus: [
      {
        id: 31,
        href: "/#",
        name: "Communication Crossroad",
        desc: {
          title: "Title1",
          content:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra",
        },
      },
      {
        id: 32,
        href: "/#",
        name: "Facilitation Freeway",
        desc: {
          title: "Title2",
          content:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra",
        },
      },
      {
        id: 33,
        href: "/job-offers",
        name: "Job Offers",
        desc: {
          title: "Title3",
          content:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra",
        },
      },
      {
        id: 34,
        href: "/events",
        name: "Events",
        desc: {
          title: "Title4",
          content:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra",
        },
      },
    ],
  },
  {
    id: 4,
    href: "/tuum",
    name: "TUUM",
    subMenus: [
      {
        id: 41,
        href: "/#",
        name: "Professor TUUM",
        desc: {
          title: "Title",
          content:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra",
        },
      },
      {
        id: 42,
        href: "/#",
        name: "Tagline",
        desc: {
          title: "Title",
          content:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra",
        },
      },
    ],
  },
  {
    id: 5,
    href: "/publications",
    name: "Publications",
    subMenus: [
      {
        id: 51,
        href: "/articles",
        name: "Essays and Articles",
        desc: null,
      },
      {
        id: 52,
        href: "/identity-chart",
        name: "Identity Chart",
        desc: null,
      },
      {
        id: 53,
        href: "/news",
        name: "News",
        desc: null,
      },
      {
        id: 54,
        href: "/#",
        name: "Library",
        desc: null,
      },
    ],
  },
  {
    id: 6,
    href: "/about",
    name: "About",
    subMenus: [
      {
        id: 61,
        href: "/brand-story",
        name: "Brand Story",
        desc: null,
      },
      {
        id: 62,
        href: "/vision-mission",
        name: "Vision & Mission",
        desc: null,
      },
      {
        id: 63,
        href: "/our-legality-and-legitimacy",
        name: "Our Legality and Legitimacy",
        desc: null,
      },
      {
        id: 64,
        href: "/policies-and-regulations",
        name: "Policies and Regulations",
        desc: null,
      },
    ],
  },
];

const policiesMenu = [
  {
    id: 1,
    title: "Total Title 1",
    path: "/policies-and-regulations/total-title-1",
  },
  {
    id: 2,
    title: "Total Title 2",
    path: "/policies-and-regulations/total-title-2",
  },
  {
    id: 3,
    title: "Total Title 3",
    path: "/policies-and-regulations/total-title-3",
  },
  {
    id: 4,
    title: "Total Title 4",
    path: "/policies-and-regulations/total-title-4",
  },
  {
    id: 5,
    title: "Total Title 5",
    path: "/policies-and-regulations/total-title-5",
  },
];

const orgChart = {
  name: "CAMA College",
  children: [
    {
      name: "Academic Identity",
      children: [
        {
          name: "Management Sciences",
          children: [
            { name: "Traditional Arm" },
            { name: "Multidisciplinary Arm" },
          ],
        },
      ],
    },
    {
      name: "Social Identity",
      children: [{ name: "Motivational Arm" }, { name: "Philanthropic Arm" }],
    },
    {
      name: "Professional Identity",
      children: [{ name: "Consultative / Advisory Arm" }],
    },
    
  ],
};

const articles = [
  {
    id: 1,
    type: "Paper",
    title: "AI Security Continuum: Concept and Challenges 1",
    desc: "Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat duis. Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in",
    year: 2024,
    author: "Rachael L. Fleurence, Xiaoyan Wang, Jagpreet Chhatwal",
    open: true,
  },
  {
    id: 2,
    type: "Review",
    title: "AI Security Continuum: Concept and Challenges 2",
    desc: "Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat duis. Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placeratLorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat duis. Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat",
    year: 2025,
    author: "Rachael L. Fleurence, Xiaoyan Wang, Jagpreet Chhatwal",
    open: false,
  },
  {
    id: 3,
    type: "Paper",
    title: "AI Security Continuum: Concept and Challenges 3",
    desc: "Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat duis. Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in",
    year: 2023,
    author: "Rachael L. Fleurence, Xiaoyan Wang, Jagpreet Chhatwal",
    open: false,
  },
  {
    id: 4,
    type: "Paper",
    title: "AI Security Continuum: Concept and Challenges 4",
    desc: "Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat duis. Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat",
    year: 2024,
    author: "Rachael L. Fleurence, Xiaoyan Wang, Jagpreet Chhatwal",
    open: false,
  },
  {
    id: 5,
    type: "Paper",
    title: "AI Security Continuum: Concept and Challenges 5",
    desc: "Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat duis. Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat",
    year: 2024,
    author: "Rachael L. Fleurence, Xiaoyan Wang, Jagpreet Chhatwal",
    open: false,
  },
  {
    id: 6,
    type: "Paper",
    title: "AI Security Continuum: Concept and Challenges 6",
    desc: "Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat duis. Lorem ipsum dolor sit amet consectetur. Quam elit lacus praesent ac enim. Pellentesque volutpat sagittis ullamcorper orci viverra dapibus sit. Sollicitudin tortor ut sem dictum odio in. Ullamcorper cursus auctor habitasse malesuada vel faucibus urna placerat",
    year: 2024,
    author: "Rachael L. Fleurence, Xiaoyan Wang, Jagpreet Chhatwal",
    open: false,
  },
];

const programsInProgress = [
  {
    id: 1,
    coverImg: "c4",
    name: "Name of Program1",
    level: "Expert",
    type: "Self Study",
    type2: "Career",
    duration: 20,
    progress: 67,
    publishDate: "2024-12-01",
    category: "IT & AI",
    contents: [
      {
        id: 1,
        title: "Subject Title 1",
        lessons: [
          {
            id: 11,
            title: "Lesson Title 1-1",
            type: "video",
            content: "Title Of Lesson 1-1",
            passed: 1,
          },
          {
            id: 12,
            title: "Lesson Title 1-2",
            type: "video",
            content: "Title Of Lesson 1-2",
            passed: 1,
          },
          {
            id: 13,
            title: "Lesson Title 1-3",
            type: "video",
            content: "Title Of Lesson 1-3",
            passed: 1,
          },
          {
            id: 14,
            title: "Lesson Title 1-4",
            type: "reading",
            content: "Title Of Lesson 1-4",
            passed: 0,
          },
          {
            id: 15,
            title: "Lesson Title 1-5",
            type: "video",
            content: "Title Of Lesson 1-5",
            passed: -1,
          },
          {
            id: 16,
            title: "Lesson Title 1-6",
            type: "video",
            content: "Title Of Lesson 1-6",
            passed: -1,
          },
          {
            id: 17,
            title: "Lesson Title 1-7",
            type: "video",
            content: "Title Of Lesson 1-7",
            passed: -1,
          },
          {
            id: 18,
            title: "Lesson Title 1-8",
            type: "video",
            content: "Title Of Lesson 1-8",
            passed: -1,
          },
          {
            id: 19,
            title: "Lesson Title 1-9",
            type: "video",
            content: "Title Of Lesson 1-9",
            passed: -1,
          },
          {
            id: 110,
            title: "Lesson Title 1-10",
            type: "video",
            content: "Title Of Lesson 1-10",
            passed: -1,
          },
          {
            id: 111,
            title: "Lesson Title 1-11",
            type: "video",
            content: "Title Of Lesson 1-11",
            passed: -1,
          },
          {
            id: 112,
            title: "Lesson Title 1-12",
            type: "video",
            content: "Title Of Lesson 1-12",
            passed: -1,
          },
        ],
      },
      {
        id: 2,
        title: "Subject Title 2",
        lessons: [
          {
            id: 21,
            title: "Lesson Title 2-1",
            type: "video",
            content: "Title Of Lesson 2-1",
            passed: 1,
          },
          {
            id: 22,
            title: "Lesson Title 2-2",
            type: "video",
            content: "Title Of Lesson 2-2",
            passed: 1,
          },
          {
            id: 23,
            title: "Lesson Title 2-3",
            type: "video",
            content: "Title Of Lesson 2-3",
            passed: 1,
          },
          {
            id: 24,
            title: "Lesson Title 2-4",
            type: "reading",
            content: "Title Of Lesson 2-4",
            passed: 0,
          },
          {
            id: 25,
            title: "Lesson Title 2-5",
            type: "video",
            content: "Title Of Lesson 2-5",
            passed: -1,
          },
          {
            id: 26,
            title: "Lesson Title 2-6",
            type: "video",
            content: "Title Of Lesson 2-6",
            passed: -1,
          },
          {
            id: 27,
            title: "Lesson Title 2-7",
            type: "video",
            content: "Title Of Lesson 2-7",
            passed: -1,
          },
          {
            id: 28,
            title: "Lesson Title 2-8",
            type: "video",
            content: "Title Of Lesson 2-8",
            passed: -1,
          },
          {
            id: 29,
            title: "Lesson Title 2-9",
            type: "video",
            content: "Title Of Lesson 2-9",
            passed: -1,
          },
          {
            id: 210,
            title: "Lesson Title 2-10",
            type: "video",
            content: "Title Of Lesson 2-10",
            passed: -1,
          },
          {
            id: 211,
            title: "Lesson Title 2-11",
            type: "video",
            content: "Title Of Lesson 2-11",
            passed: -1,
          },
          {
            id: 212,
            title: "Lesson Title 2-12",
            type: "video",
            content: "Title Of Lesson 2-12",
            passed: -1,
          },
        ],
      },
      {
        id: 3,
        title: "Subject Title 3",
        lessons: [
          {
            id: 31,
            title: "Lesson Title 3-1",
            type: "video",
            content: "Title Of Lesson 3-1",
            passed: 1,
          },
          {
            id: 32,
            title: "Lesson Title 3-2",
            type: "video",
            content: "Title Of Lesson 3-2",
            passed: 1,
          },
          {
            id: 33,
            title: "Lesson Title 3-3",
            type: "video",
            content: "Title Of Lesson 3-3",
            passed: 1,
          },
          {
            id: 34,
            title: "Lesson Title 3-4",
            type: "reading",
            content: "Title Of Lesson 3-4",
            passed: 0,
          },
          {
            id: 35,
            title: "Lesson Title 3-5",
            type: "video",
            content: "Title Of Lesson 3-5",
            passed: -1,
          },
          {
            id: 36,
            title: "Lesson Title 3-6",
            type: "video",
            content: "Title Of Lesson 3-6",
            passed: -1,
          },
          {
            id: 37,
            title: "Lesson Title 3-7",
            type: "video",
            content: "Title Of Lesson 3-7",
            passed: -1,
          },
          {
            id: 38,
            title: "Lesson Title 3-8",
            type: "video",
            content: "Title Of Lesson 3-8",
            passed: -1,
          },
          {
            id: 39,
            title: "Lesson Title 3-9",
            type: "video",
            content: "Title Of Lesson 3-9",
            passed: -1,
          },
          {
            id: 310,
            title: "Lesson Title 3-10",
            type: "video",
            content: "Title Of Lesson 3-10",
            passed: -1,
          },
          {
            id: 311,
            title: "Lesson Title 3-11",
            type: "video",
            content: "Title Of Lesson 3-11",
            passed: -1,
          },
          {
            id: 312,
            title: "Lesson Title 3-12",
            type: "video",
            content: "Title Of Lesson 3-12",
            passed: -1,
          },
        ],
      },
    ],
  },
  {
    id: 2,
    coverImg: "c1",
    name: "Name of Program2",
    level: "Expert",
    type: "Self Study",
    type2: "Career",
    duration: 20,
    progress: 50,
    publishDate: "2024-12-01",
    category: "Bussinse",
    contents: [
      {
        id: 1,
        title: "Subject Title 1",
        lessons: [
          {
            id: 11,
            title: "Lesson Title 1-1",
            type: "video",
            content: "Title Of Lesson 1-1",
            passed: 1,
          },
          {
            id: 12,
            title: "Lesson Title 1-2",
            type: "video",
            content: "Title Of Lesson 1-2",
            passed: 1,
          },
          {
            id: 13,
            title: "Lesson Title 1-3",
            type: "video",
            content: "Title Of Lesson 1-3",
            passed: 1,
          },
          {
            id: 14,
            title: "Lesson Title 1-4",
            type: "reading",
            content: "Title Of Lesson 1-4",
            passed: 0,
          },
          {
            id: 15,
            title: "Lesson Title 1-5",
            type: "video",
            content: "Title Of Lesson 1-5",
            passed: -1,
          },
          {
            id: 16,
            title: "Lesson Title 1-6",
            type: "video",
            content: "Title Of Lesson 1-6",
            passed: -1,
          },
          {
            id: 17,
            title: "Lesson Title 1-7",
            type: "video",
            content: "Title Of Lesson 1-7",
            passed: -1,
          },
          {
            id: 18,
            title: "Lesson Title 1-8",
            type: "video",
            content: "Title Of Lesson 1-8",
            passed: -1,
          },
          {
            id: 19,
            title: "Lesson Title 1-9",
            type: "video",
            content: "Title Of Lesson 1-9",
            passed: -1,
          },
          {
            id: 110,
            title: "Lesson Title 1-10",
            type: "video",
            content: "Title Of Lesson 1-10",
            passed: -1,
          },
          {
            id: 111,
            title: "Lesson Title 1-11",
            type: "video",
            content: "Title Of Lesson 1-11",
            passed: -1,
          },
          {
            id: 112,
            title: "Lesson Title 1-12",
            type: "video",
            content: "Title Of Lesson 1-12",
            passed: -1,
          },
        ],
      },
      {
        id: 2,
        title: "Subject Title 2",
        lessons: [
          {
            id: 21,
            title: "Lesson Title 2-1",
            type: "video",
            content: "Title Of Lesson 2-1",
            passed: 1,
          },
          {
            id: 22,
            title: "Lesson Title 2-2",
            type: "video",
            content: "Title Of Lesson 2-2",
            passed: 1,
          },
          {
            id: 23,
            title: "Lesson Title 2-3",
            type: "video",
            content: "Title Of Lesson 2-3",
            passed: 1,
          },
          {
            id: 24,
            title: "Lesson Title 2-4",
            type: "reading",
            content: "Title Of Lesson 2-4",
            passed: 0,
          },
          {
            id: 25,
            title: "Lesson Title 2-5",
            type: "video",
            content: "Title Of Lesson 2-5",
            passed: -1,
          },
          {
            id: 26,
            title: "Lesson Title 2-6",
            type: "video",
            content: "Title Of Lesson 2-6",
            passed: -1,
          },
          {
            id: 27,
            title: "Lesson Title 2-7",
            type: "video",
            content: "Title Of Lesson 2-7",
            passed: -1,
          },
          {
            id: 28,
            title: "Lesson Title 2-8",
            type: "video",
            content: "Title Of Lesson 2-8",
            passed: -1,
          },
          {
            id: 29,
            title: "Lesson Title 2-9",
            type: "video",
            content: "Title Of Lesson 2-9",
            passed: -1,
          },
          {
            id: 210,
            title: "Lesson Title 2-10",
            type: "video",
            content: "Title Of Lesson 2-10",
            passed: -1,
          },
          {
            id: 211,
            title: "Lesson Title 2-11",
            type: "video",
            content: "Title Of Lesson 2-11",
            passed: -1,
          },
          {
            id: 212,
            title: "Lesson Title 2-12",
            type: "video",
            content: "Title Of Lesson 2-12",
            passed: -1,
          },
        ],
      },
      {
        id: 3,
        title: "Subject Title 3",
        lessons: [
          {
            id: 31,
            title: "Lesson Title 3-1",
            type: "video",
            content: "Title Of Lesson 3-1",
            passed: 1,
          },
          {
            id: 32,
            title: "Lesson Title 3-2",
            type: "video",
            content: "Title Of Lesson 3-2",
            passed: 1,
          },
          {
            id: 33,
            title: "Lesson Title 3-3",
            type: "video",
            content: "Title Of Lesson 3-3",
            passed: 1,
          },
          {
            id: 34,
            title: "Lesson Title 3-4",
            type: "reading",
            content: "Title Of Lesson 3-4",
            passed: 0,
          },
          {
            id: 35,
            title: "Lesson Title 3-5",
            type: "video",
            content: "Title Of Lesson 3-5",
            passed: -1,
          },
          {
            id: 36,
            title: "Lesson Title 3-6",
            type: "video",
            content: "Title Of Lesson 3-6",
            passed: -1,
          },
          {
            id: 37,
            title: "Lesson Title 3-7",
            type: "video",
            content: "Title Of Lesson 3-7",
            passed: -1,
          },
          {
            id: 38,
            title: "Lesson Title 3-8",
            type: "video",
            content: "Title Of Lesson 3-8",
            passed: -1,
          },
          {
            id: 39,
            title: "Lesson Title 3-9",
            type: "video",
            content: "Title Of Lesson 3-9",
            passed: -1,
          },
          {
            id: 310,
            title: "Lesson Title 3-10",
            type: "video",
            content: "Title Of Lesson 3-10",
            passed: -1,
          },
          {
            id: 311,
            title: "Lesson Title 3-11",
            type: "video",
            content: "Title Of Lesson 3-11",
            passed: -1,
          },
          {
            id: 312,
            title: "Lesson Title 3-12",
            type: "video",
            content: "Title Of Lesson 3-12",
            passed: -1,
          },
        ],
      },
    ],
  },
  {
    id: 3,
    coverImg: "c1",
    name: "Name of Program3",
    level: "Expert",
    type: "Self Study",
    type2: "Career",
    duration: 20,
    progress: 98,
    publishDate: "2024-12-01",
    category: "IT & AI",
    contents: [
      {
        id: 1,
        title: "Subject Title 1",
        lessons: [
          {
            id: 11,
            title: "Lesson Title 1-1",
            type: "video",
            content: "Title Of Lesson 1-1",
            passed: 1,
          },
          {
            id: 12,
            title: "Lesson Title 1-2",
            type: "video",
            content: "Title Of Lesson 1-2",
            passed: 1,
          },
          {
            id: 13,
            title: "Lesson Title 1-3",
            type: "video",
            content: "Title Of Lesson 1-3",
            passed: 1,
          },
          {
            id: 14,
            title: "Lesson Title 1-4",
            type: "reading",
            content: "Title Of Lesson 1-4",
            passed: 0,
          },
          {
            id: 15,
            title: "Lesson Title 1-5",
            type: "video",
            content: "Title Of Lesson 1-5",
            passed: -1,
          },
          {
            id: 16,
            title: "Lesson Title 1-6",
            type: "video",
            content: "Title Of Lesson 1-6",
            passed: -1,
          },
          {
            id: 17,
            title: "Lesson Title 1-7",
            type: "video",
            content: "Title Of Lesson 1-7",
            passed: -1,
          },
          {
            id: 18,
            title: "Lesson Title 1-8",
            type: "video",
            content: "Title Of Lesson 1-8",
            passed: -1,
          },
          {
            id: 19,
            title: "Lesson Title 1-9",
            type: "video",
            content: "Title Of Lesson 1-9",
            passed: -1,
          },
          {
            id: 110,
            title: "Lesson Title 1-10",
            type: "video",
            content: "Title Of Lesson 1-10",
            passed: -1,
          },
          {
            id: 111,
            title: "Lesson Title 1-11",
            type: "video",
            content: "Title Of Lesson 1-11",
            passed: -1,
          },
          {
            id: 112,
            title: "Lesson Title 1-12",
            type: "video",
            content: "Title Of Lesson 1-12",
            passed: -1,
          },
        ],
      },
      {
        id: 2,
        title: "Subject Title 2",
        lessons: [
          {
            id: 21,
            title: "Lesson Title 2-1",
            type: "video",
            content: "Title Of Lesson 2-1",
            passed: 1,
          },
          {
            id: 22,
            title: "Lesson Title 2-2",
            type: "video",
            content: "Title Of Lesson 2-2",
            passed: 1,
          },
          {
            id: 23,
            title: "Lesson Title 2-3",
            type: "video",
            content: "Title Of Lesson 2-3",
            passed: 1,
          },
          {
            id: 24,
            title: "Lesson Title 2-4",
            type: "reading",
            content: "Title Of Lesson 2-4",
            passed: 0,
          },
          {
            id: 25,
            title: "Lesson Title 2-5",
            type: "video",
            content: "Title Of Lesson 2-5",
            passed: -1,
          },
          {
            id: 26,
            title: "Lesson Title 2-6",
            type: "video",
            content: "Title Of Lesson 2-6",
            passed: -1,
          },
          {
            id: 27,
            title: "Lesson Title 2-7",
            type: "video",
            content: "Title Of Lesson 2-7",
            passed: -1,
          },
          {
            id: 28,
            title: "Lesson Title 2-8",
            type: "video",
            content: "Title Of Lesson 2-8",
            passed: -1,
          },
          {
            id: 29,
            title: "Lesson Title 2-9",
            type: "video",
            content: "Title Of Lesson 2-9",
            passed: -1,
          },
          {
            id: 210,
            title: "Lesson Title 2-10",
            type: "video",
            content: "Title Of Lesson 2-10",
            passed: -1,
          },
          {
            id: 211,
            title: "Lesson Title 2-11",
            type: "video",
            content: "Title Of Lesson 2-11",
            passed: -1,
          },
          {
            id: 212,
            title: "Lesson Title 2-12",
            type: "video",
            content: "Title Of Lesson 2-12",
            passed: -1,
          },
        ],
      },
      {
        id: 3,
        title: "Subject Title 3",
        lessons: [
          {
            id: 31,
            title: "Lesson Title 3-1",
            type: "video",
            content: "Title Of Lesson 3-1",
            passed: 1,
          },
          {
            id: 32,
            title: "Lesson Title 3-2",
            type: "video",
            content: "Title Of Lesson 3-2",
            passed: 1,
          },
          {
            id: 33,
            title: "Lesson Title 3-3",
            type: "video",
            content: "Title Of Lesson 3-3",
            passed: 1,
          },
          {
            id: 34,
            title: "Lesson Title 3-4",
            type: "reading",
            content: "Title Of Lesson 3-4",
            passed: 0,
          },
          {
            id: 35,
            title: "Lesson Title 3-5",
            type: "video",
            content: "Title Of Lesson 3-5",
            passed: -1,
          },
          {
            id: 36,
            title: "Lesson Title 3-6",
            type: "video",
            content: "Title Of Lesson 3-6",
            passed: -1,
          },
          {
            id: 37,
            title: "Lesson Title 3-7",
            type: "video",
            content: "Title Of Lesson 3-7",
            passed: -1,
          },
          {
            id: 38,
            title: "Lesson Title 3-8",
            type: "video",
            content: "Title Of Lesson 3-8",
            passed: -1,
          },
          {
            id: 39,
            title: "Lesson Title 3-9",
            type: "video",
            content: "Title Of Lesson 3-9",
            passed: -1,
          },
          {
            id: 310,
            title: "Lesson Title 3-10",
            type: "video",
            content: "Title Of Lesson 3-10",
            passed: -1,
          },
          {
            id: 311,
            title: "Lesson Title 3-11",
            type: "video",
            content: "Title Of Lesson 3-11",
            passed: -1,
          },
          {
            id: 312,
            title: "Lesson Title 3-12",
            type: "video",
            content: "Title Of Lesson 3-12",
            passed: -1,
          },
        ],
      },
    ],
  },
  {
    id: 4,
    coverImg: "c1",
    name: "Name of Program4",
    level: "Expert",
    type: "Self Study",
    type2: "Career",
    duration: 20,
    progress: 40,
    publishDate: "2024-12-01",
    category: "IT & AI",
    contents: [
      {
        id: 1,
        title: "Subject Title 1",
        lessons: [
          {
            id: 11,
            title: "Lesson Title 1-1",
            type: "video",
            content: "Title Of Lesson 1-1",
            passed: 1,
          },
          {
            id: 12,
            title: "Lesson Title 1-2",
            type: "video",
            content: "Title Of Lesson 1-2",
            passed: 1,
          },
          {
            id: 13,
            title: "Lesson Title 1-3",
            type: "video",
            content: "Title Of Lesson 1-3",
            passed: 1,
          },
          {
            id: 14,
            title: "Lesson Title 1-4",
            type: "reading",
            content: "Title Of Lesson 1-4",
            passed: 0,
          },
          {
            id: 15,
            title: "Lesson Title 1-5",
            type: "video",
            content: "Title Of Lesson 1-5",
            passed: -1,
          },
          {
            id: 16,
            title: "Lesson Title 1-6",
            type: "video",
            content: "Title Of Lesson 1-6",
            passed: -1,
          },
          {
            id: 17,
            title: "Lesson Title 1-7",
            type: "video",
            content: "Title Of Lesson 1-7",
            passed: -1,
          },
          {
            id: 18,
            title: "Lesson Title 1-8",
            type: "video",
            content: "Title Of Lesson 1-8",
            passed: -1,
          },
          {
            id: 19,
            title: "Lesson Title 1-9",
            type: "video",
            content: "Title Of Lesson 1-9",
            passed: -1,
          },
          {
            id: 110,
            title: "Lesson Title 1-10",
            type: "video",
            content: "Title Of Lesson 1-10",
            passed: -1,
          },
          {
            id: 111,
            title: "Lesson Title 1-11",
            type: "video",
            content: "Title Of Lesson 1-11",
            passed: -1,
          },
          {
            id: 112,
            title: "Lesson Title 1-12",
            type: "video",
            content: "Title Of Lesson 1-12",
            passed: -1,
          },
        ],
      },
      {
        id: 2,
        title: "Subject Title 2",
        lessons: [
          {
            id: 21,
            title: "Lesson Title 2-1",
            type: "video",
            content: "Title Of Lesson 2-1",
            passed: 1,
          },
          {
            id: 22,
            title: "Lesson Title 2-2",
            type: "video",
            content: "Title Of Lesson 2-2",
            passed: 1,
          },
          {
            id: 23,
            title: "Lesson Title 2-3",
            type: "video",
            content: "Title Of Lesson 2-3",
            passed: 1,
          },
          {
            id: 24,
            title: "Lesson Title 2-4",
            type: "reading",
            content: "Title Of Lesson 2-4",
            passed: 0,
          },
          {
            id: 25,
            title: "Lesson Title 2-5",
            type: "video",
            content: "Title Of Lesson 2-5",
            passed: -1,
          },
          {
            id: 26,
            title: "Lesson Title 2-6",
            type: "video",
            content: "Title Of Lesson 2-6",
            passed: -1,
          },
          {
            id: 27,
            title: "Lesson Title 2-7",
            type: "video",
            content: "Title Of Lesson 2-7",
            passed: -1,
          },
          {
            id: 28,
            title: "Lesson Title 2-8",
            type: "video",
            content: "Title Of Lesson 2-8",
            passed: -1,
          },
          {
            id: 29,
            title: "Lesson Title 2-9",
            type: "video",
            content: "Title Of Lesson 2-9",
            passed: -1,
          },
          {
            id: 210,
            title: "Lesson Title 2-10",
            type: "video",
            content: "Title Of Lesson 2-10",
            passed: -1,
          },
          {
            id: 211,
            title: "Lesson Title 2-11",
            type: "video",
            content: "Title Of Lesson 2-11",
            passed: -1,
          },
          {
            id: 212,
            title: "Lesson Title 2-12",
            type: "video",
            content: "Title Of Lesson 2-12",
            passed: -1,
          },
        ],
      },
      {
        id: 3,
        title: "Subject Title 3",
        lessons: [
          {
            id: 31,
            title: "Lesson Title 3-1",
            type: "video",
            content: "Title Of Lesson 3-1",
            passed: 1,
          },
          {
            id: 32,
            title: "Lesson Title 3-2",
            type: "video",
            content: "Title Of Lesson 3-2",
            passed: 1,
          },
          {
            id: 33,
            title: "Lesson Title 3-3",
            type: "video",
            content: "Title Of Lesson 3-3",
            passed: 1,
          },
          {
            id: 34,
            title: "Lesson Title 3-4",
            type: "reading",
            content: "Title Of Lesson 3-4",
            passed: 0,
          },
          {
            id: 35,
            title: "Lesson Title 3-5",
            type: "video",
            content: "Title Of Lesson 3-5",
            passed: -1,
          },
          {
            id: 36,
            title: "Lesson Title 3-6",
            type: "video",
            content: "Title Of Lesson 3-6",
            passed: -1,
          },
          {
            id: 37,
            title: "Lesson Title 3-7",
            type: "video",
            content: "Title Of Lesson 3-7",
            passed: -1,
          },
          {
            id: 38,
            title: "Lesson Title 3-8",
            type: "video",
            content: "Title Of Lesson 3-8",
            passed: -1,
          },
          {
            id: 39,
            title: "Lesson Title 3-9",
            type: "video",
            content: "Title Of Lesson 3-9",
            passed: -1,
          },
          {
            id: 310,
            title: "Lesson Title 3-10",
            type: "video",
            content: "Title Of Lesson 3-10",
            passed: -1,
          },
          {
            id: 311,
            title: "Lesson Title 3-11",
            type: "video",
            content: "Title Of Lesson 3-11",
            passed: -1,
          },
          {
            id: 312,
            title: "Lesson Title 3-12",
            type: "video",
            content: "Title Of Lesson 3-12",
            passed: -1,
          },
        ],
      },
    ],
  },
];

const days = [
  { id: 4, date: "2025-05-05", haveClass: false, newEvents: [] },
  { id: 5, date: "2025-05-06", haveClass: true, newEvents: [] },
  { id: 6, date: "2025-05-07", haveClass: false, newEvents: [] },
  { id: 7, date: "2025-05-08", haveClass: false, newEvents: [] },
  { id: 8, date: "2025-05-09", haveClass: true, newEvents: [] },
  { id: 9, date: "2025-05-10", haveClass: false, newEvents: [] },
  { id: 10, date: "2025-05-11", haveClass: false, newEvents: [] },
  { id: 11, date: "2025-05-12", haveClass: false, newEvents: [1] },
  { id: 12, date: "2025-05-13", haveClass: false, newEvents: [] },
  { id: 13, date: "2025-05-14", haveClass: false, newEvents: [] },
  { id: 14, date: "2025-05-15", haveClass: false, newEvents: [] },
  { id: 15, date: "2025-05-16", haveClass: false, newEvents: [] },
  { id: 16, date: "2025-05-17", haveClass: false, newEvents: [] },
  { id: 17, date: "2025-05-18", haveClass: false, newEvents: [] },
  { id: 18, date: "2025-05-19", haveClass: false, newEvents: [] },
  { id: 19, date: "2025-05-20", haveClass: false, newEvents: [] },
  { id: 20, date: "2025-05-21", haveClass: false, newEvents: [] },
  { id: 20, date: "2025-05-22", haveClass: false, newEvents: [] },
  { id: 20, date: "2025-05-23", haveClass: false, newEvents: [] },
  { id: 20, date: "2025-05-24", haveClass: false, newEvents: [] },
];

const LIMITOfLOADEDLIST = 12;
const LIMITOfLOADEDLISTINONEPAGE = 47;
const LIMITNUMBEROFSCROLL = 3;

export {
  news,
  days,
  posts,
  events,
  comments,
  articles,
  programs,
  orgChart,
  jobOffers,
  categories,
  newsGroups,
  headerMenus,
  policiesMenu,
  transactions,
  LIMITOfLOADEDLIST,
  programsInProgress,
  LIMITNUMBEROFSCROLL,
  LIMITOfLOADEDLISTINONEPAGE,
};
